### ISSUE TITLE
Indicate that propagated error is the "Relative percent error"

### ISSUE THREAD

**Issue by jamesorr** [KatiRG/marineCO2ErrorPropagation#4]
Cathy,
It should be indicated, perhaps in the title of the plot (or in a figure legend) that the error that is shown in the relative percent error.  That is, it is 100 times the ratio of the absolute error divided by the value of the computed variable.

**Comment by KatiRG** [comment]
I added this as the intro text:

"Displays the relative percent error (100% * absolute error/computed variable value) of the computed variable."

and then the chart title shows:

"Relative percent error for [varname]"

**Comment by jamesorr** [comment]
Thanks!

Thinking about this a little more, I think it would be better to inverse the first 2 words,, i.e, to change the title to "Percent relative error for [varname]".
