### ISSUE TITLE
add checkbox & input box to allow users to change default errors in epK vector

### ISSUE THREAD

**Issue by jamesorr** [KatiRG/marineCO2ErrorPropagation#9]
Hi Cathy,

Users would find this suggested feature useful, especially advanced ones who want to alter these vaules.  The checkbox should have the label 'Change default uncertainties for constants (epK0, epK1, epK2, epKb, epKw, epKspa, epKspc, eBt)'.

If you don't have time for this, i could perhaps give it a try, make a test, and issue a Pull Request.

Thanks!

James

**Comment by jamesorr** [comment]
This is the same idea already mention in Issue #6

**Comment by KatiRG** [comment]
I have configured 8 text boxes for each of the constants to appear after user checks "Change default uncertainties" checkbox. See code in branch epkerrors. 

But you will have to tell me where these inputs are used in the calculations.

**Comment by KatiRG** [comment]
Done. Also closes #6
